# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod verify
builds:
  -
    main: ./cmd/wrkoracle/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=WrkOracle
      - -X github.com/cosmos/cosmos-sdk/version.ServerName=wrkoracle
      - -X github.com/cosmos/cosmos-sdk/version.ClientName=wrkoracle
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit=

archives:
  -
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x86_64
      darwin: osx
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
